What is docker
docker-seminar/docker-basics pull request #16
Opened 2024-12-13 19:16 UTC by Minkyuuu

도커의 정의와 사용 목적

2024-12-17 01:21 UTC, kimseungbin requested changes
Merge base branch 를 `main` -> `mkb/main` 변경 요망

2024-12-17 01:21 UTC, kimseungbin commented on What-is-docker.md
> +도커는 응용 프로그램과 필요한 환경을 <ins>컨테이너</ins>라는 단위로 묶어 패키징, 배포, 실행할 수 있게 도와주는 플랫폼입니다.
**<ins>Underline**</ins>: 주로 삽입된 항목 강조하기 위해 사용. 혹은 하이퍼링크나 마우스오버 인터랙션으로 혼동될 수 있음.

단어나 표현을 강조할 때는 **bold** 사용이 일반적

2024-12-20 03:47 UTC, Minkyuuu reviewed
- base branch 변경 완료
- bold체 변경 완료

2024-12-20 05:27 UTC, kimseungbin approved these changes
LGTM

2024-12-20 05:27 UTC, merged