Add test.txt file for testing
docker-seminar/docker-basics pull request #20
Opened 2024-12-17 07:22 UTC by Minkyuuu

2024-12-17 08:09 UTC, Minkyuuu commented
Add feature_request.md

2024-12-17 08:16 UTC, kimseungbin requested changes
- 불필요한 커밋을 drop 해주세요
  - 254fe3373cc4d88836e207f6590e8829c1243a95
- PR 제목을 수정해주세요.
- PR 본문에 Close keyword 추가해주세요.
  ```Markdown
  - Close #이슈번호
  ```

2024-12-17 08:16 UTC, kimseungbin commented on feature_request.md
> +title: ''
타이틀을 추가해주세요.

2024-12-17 08:19 UTC, kimseungbin commented
JetBrain's 로 커밋 삭제하는 방법

1. 커밋 할 커밋 우클릭

![image](https://github.com/user-attachments/assets/7bba89c4-96f4-4482-9e5f-eed628a74165)

2. Drop commit 클릭

![image](https://github.com/user-attachments/assets/63c4e6ab-ed51-4334-98d3-8f9b73b37397)


3. OK

4. 로컬과 원격 브랜치 분리확인

![image](https://github.com/user-attachments/assets/c09db315-33fe-4519-a31d-c1f623998edb)


- 로컬에는 Add test.txt file for testing 이 없음


5. force push

```
git push --force
```

혹은 JetBrains push 모달에서 Force Push 버튼 클릭

![image](https://github.com/user-attachments/assets/ac1094f9-e4cb-4c74-9ca4-eedd3a586c35)

2024-12-18 07:26 UTC, kimseungbin approved these changes
LGTM

2024-12-18 07:42 UTC, merged